# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
 #---------------------a----------------------------------------
actualizar=Actualizar
accederAplicacion=Volver acceder a la aplicaci\u00f3n
agregarBodega=Agregar Bodega
agregarOperador=Agregar Operador
agregarPerfil=Agregar Perfil
agregarPrensa=Agregar Prensa
agregarUsuario=Agregar Usuario
armado=Armado
 #---------------------b----------------------------------------
bobinas=Bobinas
bodega=Bodega
 #---------------------c----------------------------------------
canton=Canton
cancelar=Cancelar
cantidad=Cantidad
cantidadNoConforme=Cantidad NoConforme
cantidadEjecutada= Cantidad Ejecutada
cantidadPlacas= Cantidad Placas
cantidadPlanificada=Cantidad Planificada
cerrar=Cerrar
circunscripcion=Circuns
compaginados=Compaginados
#----------------------d----------------------------------------
descripcion=Descripcion
desde=Desde
dignidad=Dignidad
disenador=Dise\u00f1ador
documentos=Documentos
documento=Documento
#-----------------------e---------------------------------------
estado=Estado
entregados=Entregados
#-----------------------f---------------------------------------
faltanteCompaginados=Faltante Compaginados
faltanteImpresos=Faltante impresos
faltanteEntregados=Faltante Entregados
FaltantePreimpresos=Faltante Pre impresos
fecha=Fecha
fechaRegistro=FechaReg
formatoImpresion=Formato Impresi\u00f3n
formatoPapel=Formato Papel
formatoPliego=Formato Pliego
formatoTerminado=Formato Terminado
#-----------------------g---------------------------------------
guardar=Guardar
#-----------------------h---------------------------------------
hasta=Hasta
#-----------------------i---------------------------------------
Idbodega=Idbodega
idDignidad=IdDignidad
IdOperador=IdOperador
idperfil=IdPerfil
idPrensa=IdPrensa
idProvincia=IdProvincia
idUsuario=IdUsuario
impresas=Impresas
impresos=Impresos
#-----------------------j---------------------------------------
juntas=Juntas
#-----------------------l---------------------------------------
lote=Lote
#-----------------------m---------------------------------------
materialConforme=Material Conforme
materialNoConforme=Material NoConforme
mensaje=Ingrese la cantidad
mensajeActualizacionEstadosSi=Se actualizo los estados
mensajeActualizacionEstadosNo=No se actualizo los estados
mensajeArmado=Ingrese el armado
mensajeBobinas=Ingrese la cantidad de bobina
mensajeCantidad=Ingrese la cantidad de documentos
mensajeCantidadFaltante=La cantidad ingresada no puede ser mayor a la faltante.
mensajeCantidadPreimpresos=Ingrese la cantidad de preimpresos
mensajeCantidadPlacas=Ingrese la cantidad de placas
mensajeCanton=Seleccione un canton
mensajeCircunscripcion=Seleccione la circunscripci\u00f3n
mensajeDescripcion=Ingrese la descripci\u00f3n
mensajeDignidad=Seleccione una dignidad
msgErrorLogin = Error! Usuario incorrecto
mensajeErrorCuentaRegistros=No se puede ingresar m\u00e1s registros ya se encuentra completo el proceso
mensajeErrorSaldoProvincia=El valor ingresado es mayor al saldo de la provincia
mensajeErrorSaldoCanton=El valor ingresado es mayor al saldo del cant\u00f3n
mensajeErrorSaldoParroquia=El valor ingresado es mayor al saldo de la parroquia
mensajeErrorSaldoProvincias=El valor ingresado es mayor al saldo acumulado de todas las provincias.
mensajeEstado=Seleccione el estado
mensajeFormato=Seleccione el formato
mensajeGuardar=Registro guardado con \u00e9xito.
mensajeGuardarError=No se guardo el registro.
mensajeMaquinaria=Ingrese el nombre de la maquinaria
mensajeMaterialConforme=Ingrese la cantidad de material conforme
mensajeMaterialNoConforme=Ingrese la cantidad de material no conforme
mensajeNombre=Ingrese los nombres
mensajeNPalet=Ingrese el n\u00famero de palet
mensajeObservacion=Ingrese la observacion
mensajeOperador=Seleccione el nombre del operador
mensajeOperadorRegistro=Ingrese el nombre del operador
mensajeProvincia=Seleccione una provincia
mensajeParroquia=Seleccione una parroquia
mensajePassword=Ingrese el password
mensajePliegos=Ingrese la cantidad de pliegos
mensajePrensa=Seleccione la prensa
mensajeProceso=Seleccione el proceso
mensajeProduccionPapeletas=Ingrese la cantidad de papeletas
mensajeSesionCaducada=La sesi\u00f3n ha caducado,por favor,pulse sobre el siguiente bot\u00f3n para volver acceder a la aplicaci\u00f3n
mensajeSeleccionarRegistro=Por favor seleccione un registro para resetear el password
mensajeTipoDocumento=Seleccione el tipo de documento
mensajeTipoOperador=Ingrese el tipo de operador
mensajeTurno=Seleccione el turno de trabajo
mensajeUsuario=Ingrese el usuario
#-----------------------n---------------------------------------
nombreCompleto=NombreCompleto
nPalet=# Palet
#-----------------------o---------------------------------------
observaciones=Observacion
operador=Operador
#-----------------------p---------------------------------------
parroquia=Parroquia
password=Password
perfil=Perfil
porcentajeImpresas=% Impresas
pliegos=Pliegos o Tiros
prelacion=Prelaci\u00f3n
prensa=Prensa
preimpresos=Pre Impresos
proceso=Proceso
produccionPapeletas=Producci\u00f3n Papeletas
produccionPapeletasMaculatura=Maculatura
provincia=Provincia
#-----------------------r---------------------------------------
resetarPassword=Resetear Password
#-----------------------s---------------------------------------
saldo=Saldo
supervisor=Supervisor
#-----------------------t---------------------------------------
tipo=Tipo
tipoDocumento=Tipo Documento
tituloPagina=SISTEMA DE PRODUCCION PAPELETAS Y DOCUMENTOS ELECTORALES
tituloPaginaDocumentos=Registro Producci\u00f3n Documentos
tituloPaginaPapeletas=Registro Papeletas
tituloPaginaPreimpresos=Registro Producci\u00f3n Preimpresos
tituloPanel=Papeletas
tituloPanelBodega=Registrar Bodega
tituloPanelBodegas=Registrar Bodegas
tituloPanelDocumentos=Documentos
tituloPanelOperador=Registrar Operador
tituloPanelPerfil=Registrar Perfiles
tituloPanelPrensa=Registrar Prensa
tituloPanelUsuarios=Registrar Usuarios
tituloPanelUsuario=Registrar Usuario
tituloReporteProduccionPapeletas=Reporte de Producci\u00f3n Papeletas 2021
tituloReportePreprensaPapeletas=Reporte de Preprensa Papeletas
tituloReportePreprensaPreimpresos=Reporte de Preprensa Preimpresos
tituloReporteProduccionDocumentos=Reporte Avance Producci\u00f3n Documentos
tituloReporteProduccionDocumentosDetalle=Reporte de Timbrados de Personal
tituloReporteProduccionPreimpresos=Reporte Producci\u00f3n Preimpresos
tituloReporteEntregaPapeletas=Reporte de entregas papeletas y documentos electorales
tituloSesionCaducada=Sesi\u00f3n Caducada
total=Total
turno=Turno
#-----------------------u---------------------------------------
usuario=Usuario
#-----------------------v---------------------------------------
validacionNumeros=Ingrese solo n\u00fameros































